Veteran/Account/urls.py
from django.urls import path
from . import views

app_name='Account'

urlpatterns=[
    path('',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    path('signup/', views.signup, name='signup'),
    path('mypage/',views.mypage, name = 'mypage' ),
    path('reqHostAthority/', views.reqHostAthority, name = 'reqHostAthority'),
    path('lookupReq/', views.lookupReq, name ='lookupReq'),
    path('approveReq/',views.approveReq,name='approveReq'),
    path('deleteReq/',views.deleteReq,name='deleteReq'),
    path('lookupRecord/', views.lookupRecord, name='lookupRecord'),
    path('lookupMyReview/', views.lookupMyReview, name='lookupMyReview'),
    path('leaveReview/', views.leaveReview, name='leaveReview'),
]

Veteran/Game/urls.py
from django.urls import path
from . import views

app_name='Game'

urlpatterns=[
    path('gamelist/', views.gamelist, name = 'gamelist'),
    path('participate/<int:id>/', views.participate, name = 'participate'),
    path('hostGame/', views.hostGame, name = 'hostGame'),
    path('registerGame/', views.registerGame, name="registerGame"),
    path('payment/', views.payment, name='payment'),
]

Veteran/Veteran/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import urls

from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.welcome , name='welcome'),
    path('accounts/',include('accounts.urls')),
    path('games/',include('games.urls')),
]

Veteran/games/urls.py
from django.urls import path
from . import views

app_name='games'


urlpatterns=[
    path('gamelist/', views.gamelist, name = 'gamelist'),
    path('participate/', views.participate, name = 'participate'),
    path('newgame/', views.newgame, name = 'newgame'),
    
]

Veteran/Game/models.py
from django.db import models
from django.utils import timezone
from Account.models import User,Host

#from Auth.models import User,Host

# Create your models here.

class Game(models.Model):
    host=models.ForeignKey('Account.Host',null=False, on_delete=models.PROTECT)
    start_datetime=models.DateTimeField(default=timezone.localtime(), null=False)
    end_datetime=models.DateTimeField(default=timezone.localtime(), null=False)
    numOfRecruitment=models.IntegerField(default=18,null=False)
    numOfParticipation=models.IntegerField(default=0,null=False)
    completed=models.BooleanField(default=False)
    
    
    def isProgressed(self):
        if self.start_datetime>timezone.localtime():
            return False
        else:
            return True
        
    def updateState(self):
        if self.isProgressed():
            self.completed=True
        return True
        
    def toDict(self):
        dictionary = {}
        dictionary['id'] = self.id
        dictionary["host"] = self.host
        dictionary["start_datetime"] = self.start_datetime.strftime("%Y-%m-%d %H:%M")
        dictionary["end_datetime"] = self.end_datetime.strftime("%Y-%m-%d %H:%M")
        dictionary["numOfRecruitment"] = self.numOfRecruitment
        dictionary["numOfParticipation"] = self.numOfParticipation
        return dictionary
    
    def toTuple(self):
        return (
            self.id,
            self.host.group_name,
            self.start_datetime,
            self.end_datetime,
            self.numOfRecruitment,
            self.numOfParticipation
        )
        
        
    
class Game_Participants(models.Model):
    game=models.ForeignKey(Game, on_delete=models.PROTECT)
    user=models.ForeignKey('Account.User', on_delete=models.CASCADE)
    
    class Meta:
        unique_together = (('game', 'user'),)
        
    def getPlayer(self):
        return [self.user.id, self.user.username]

Veteran/games/models.py
from django.db import models
from django.utils import timezone
from accounts.models import User,Host

#from Auth.models import User,Host

# Create your models here.

class Game(models.Model):
    host = models.ForeignKey(Host, on_delete=models.PROTECT)
    start_datetime = models.DateTimeField()
    end_datetime = models.DateTimeField()
    numOfRecruitment = models.IntegerField(default=18,null=False)
    numOfParticipation = models.IntegerField(default=0,null=False)
    completed = models.BooleanField(default=False)
    

    
class HostGame(models.Model):
    host = models.ForeignKey(Host, on_delete = models.PROTECT)
    game = models.ForeignKey(Game, on_delete = models.PROTECT)
        

    
class GameParticipant(models.Model):
    game = models.ForeignKey(Game, on_delete=models.PROTECT)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    class Meta:
        unique_together = (('game', 'user'),)
        
    def getPlayer(self):
        return [self.user.id, self.user.username]

Veteran/games/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator
from django.urls import reverse
from django.db import transaction
from django.contrib import messages
from django.core import serializers
from django.utils import timezone

import requests
import json
from datetime import datetime

from accounts.models import Host, User
from .models import Game, GameParticipant
from .serializers import GameSerializer


# Create your views here.
def gamelist(request):
    queryset = Game.objects.filter( start_datetime__gt = timezone.now()).order_by('start_datetime')
    serializer = GameSerializer(queryset, many=True)
    games = json.dumps(json.loads(json.dumps(serializer.data)))
    return render(request,'games/gamelist.html', {'page_obj' : games})


def newgame(request):
    hosts = Host.objects.filter(host = request.user)
    if hosts:
        if request.method == 'POST':
            host = Host.objects.get(id = request.POST['host'])
            try:
                with transaction.atomic():
                    game = Game()
                    game.host = host
                    game.start_datetime = request.POST['start_datetime']
                    game.end_datetime = request.POST['end_datetime']
                    game.numOfRecruitment = request.POST['numOfRecruitment']
                    game.save()
            except Exception as e:
                print(e)
                messages.warning(request, "해당 경기를 생성할 수 없습니다.")
                return redirect('games:newgame')
            return redirect('games:gamelist')
        elif request.method == "GET":
            hosts = serializers.serialize('json', hosts)
            return render(request, 'games/game_form.html', {'hosts' : hosts})
    else:
        return redirect('games:gamelist')
    

def participate(request):
    if request.method == "POST":
        game = Game.objects.get(id = request.POST['gameid'])
        if game:
            try:
                with transaction.atomic():
                    newParticipation = GameParticipant(game = game, user = request.user)
                    newParticipation.save()
            except Exception as e:
                messages.warning(request, "이미 참여한 경기입니다.")
                return redirect('games:gamelist')
        else:
            messages.warning(request, "해당 경기를 찾을 수 없습니다.")
        return redirect('games:gamelist')
    return redirect('games:gamelist')
            
            

Veteran/templates/games/game_form.html
{% extends 'base.html' %}
{% block head %}
{% endblock %}

{% block style %}
{% endblock %}

{% block content %}
{% load static %}
<div>
    <form action="{% url 'games:newgame' %}" method="POST">
        {% csrf_token %}
        <div>
            <h5>호스트</h5>
            <select name='host' id='host_select' required onchange="changeHostSelect()"></select>
        </div>
        <div>
            <h5>농구장 주소</h5>
            <h5>{{ host.court_location }}</h5>
        </div>
        <div>
            <h5>인원수</h5>
            <input type="number" min="1" max="18" placeholder="모집 인원" name="numOfRecruitment">
        </div>
        <div>
            <h5>시작시간</h5>
            <input type="datetime-local" id="start_datetime" name="start_datetime" oninput="setEndtime();">
        </div>
        <div>
            <h5>종료시간</h5>
            <input type="datetime-local" id="end_datetime" name="end_datetime" >
        </div>
        <button type="submit">경기 등록</button>
    </form> 
</div>
<script>
    //경기 시간 현재 시간으로 초기화
    let start_dt = document.getElementById('start_datetime');
    let end_dt = document.getElementById('end_datetime');
    let crnt_date = new Date(new Date().getTime() - new Date().getTimezoneOffset()*60000 ).toISOString().slice(0,-8);
    start_dt.value = crnt_date;
    end_dt.value = crnt_date;
    start_dt.setAttribute('min', crnt_date);
    end_dt.setAttribute('min', crnt_date);

    function setEndtime(){
        end_dt.value = document.getElementById('start_datetime').value;
        end_dt.setAttribute('min', document.getElementById('start_datetime').value);
    }

    //호스트 select 옵션 생성
    var host_select = document.getElementById('host_select');    
    var hosts = eval(JSON.parse(JSON.stringify('{{ hosts }}'.replace(/&quot;/g, '"'))));
  
    for (let i=0; i< hosts.length; ++i){
        var op = document.createElement('option');
        op.setAttribute('value', hosts[i]['pk']);
        op.innerHTML = hosts[i]['fields']['group_name'];
        host_select.appendChild(op);
    };

    

    
</script>
{% endblock %}

Veteran/templates/games/gamelist.html
{% extends 'base.html' %}
{% block head %}
<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=91ea5fd278223521e857ad81684db507&libraries=services"></script>
{% endblock %}

{% block style %}
{% endblock %}

{% block content %}

{% load static %}

<div class="wrapper">
    <div class="items" style="display : flex; flex-direction : row; flex-wrap: wrap;">
        <!--지도 표시 부분-->
        <div class="map" id='map' style="width:800px; height: 800px; margin:30px;">

        </div>

        <!--경기 리스트 부분-->
        <div class="right" id='list' style = "display : flex; flex-direction : column; min-width:500px; min-height:300px; margin:30px; padding : 30px; background-color:beige; justify-content: space-between;">
            <div>
                <h1>경기 리스트</h1>
            </div>
            <div id='gamelist' style="display:flex; flex-direction: column; justify-content: space-between;">

            </div>
            <div id='form'>
                <form id='joinform' method="POST" action="{% url 'games:participate' %}" >
                    {% csrf_token %}
                    <input id="gameid_input" name="gameid" readonly action="{% url 'games:participate' %}">
                    <p id="gameinfo"></p>
                    <button type="submit">참가신청</button>
                </form>
                <button onclick="toggleList('list')" >목록보기</button>
            </div>
            <div>
                {% if games.has_previous %}
                    <a class="page-link" style="float: left;" id="page_link" href="?page={{ games.previous_page_number }}">이전</a>
                {% else %}
                    <a class="page-link" style="float: left;" id="page_link" tabindex="-1" aria-disabled="true" href="#">이전</a>
                {% endif %}
                {{ games.number }}
                {% if games.has_next %}
                    <a class="page-link" style="float: right;" id="page_link" href="?page={{ games.next_page_number }}">다음</a>
                {% else %}
                    <a class="page-link" style="float: right;" id="page_link" tabindex="-1" aria-disabled="true" href="#">다음</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
<script>
    //경기 리스트 생성
    var objs = eval(JSON.parse(JSON.stringify('{{ page_obj }}'.replace(/&quot;/g, '"'))));
    var gamelist = document.getElementById('gamelist');
    var form = document.getElementById('form');
    
    
    window.onload = showGameList();

    function showGameList(){
        toggleList('list');
        for (let i=0; i<objs.length; ++i) {
            var elemdiv = document.createElement('div');
            var elemp = document.createElement('p');
            elemp.innerHTML = objs[i]['host']['group_name'] + " " + objs[i]['host']['court_location'] + "<br>" + objs[i]['start_datetime'] + " - " + objs[i]['end_datetime'];
            var elembut = document.createElement('button');
            elembut.value = objs[i]['id'];
            elembut.onclick = function(){showJoinForm(objs[i]['id'])};
            elembut.innerHTML = "참가";
            elemdiv.appendChild(elemp);
            elemdiv.appendChild(elembut);
            gamelist.appendChild(elemdiv);
        };
    }

    function toggleList(order){
        if (order == 'list') {
            form.style.display = "none";
            gamelist.style.display = "";
        }else{
            gamelist.style.display = "none";
            form.style.display = "";
        };
    }

    function removeAllChild(elem){
        while (elem.hasChildNodes()){
            elem.removeChild(elem.firstChild);
        }
    }

    function showJoinForm (gameid) {
        toggleList('joinform'); 
        var gameid_input = document.getElementById('gameid_input');     
        var gameinfo = document.getElementById('gameinfo');
        gameid_input.value = gameid;
        gameinfo.innerHTML = objs[gameid]['host']['group_name'] + " " + objs[gameid]['host']['court_location'] + "<br>" + objs[i]['start_datetime'] + " - " + objs[gameid]['end_datetime'];
    }


    //지도 생성
    var container = document.getElementById('map');
    var option = {
        center : new kakao.maps.LatLng(37.59727,127.05884),
        level:3
    };

    var games = [];

    const map = new kakao.maps.Map(container,option);
    const court_markers=[];

    // 주소-좌표 변환 객체 생성
    var geocoder = new kakao.maps.services.Geocoder();


    //현재 사용자 위치 좌표 반환 메소드
    function getCurrentLocation(){
        if (navigator.geolocation){
            navigator.geolocation.getCurrentPosition(function(position){
                var lat=position.coords.latitude,
                lon=position.coords.longitude;
                var locPosition=new kakao.maps.LatLng(lat,lon)
            });
        }else {
            var locPosition=new kakao.maps.LatLng(33.450701,126.590667);
        }
        return locPosition;
    }

    //사용자 위치 지도에 표시    
    if (navigator.geolocation){
        navigator.geolocation.getCurrentPosition(function(position){
            var lat=position.coords.latitude,
            lon=position.coords.longitude;
            
            var locPosition=new kakao.maps.LatLng(lat,lon),
            message='here';


            map.setCenter(locPosition);
            


            displayMarker(locPosition,message);
        });
        } 
        else {
            var locPosition=new kakao.maps.LatLng(33.450701,126.590667),
            message="error!"
            displayMarker(locPosition,message);
        }


    //마커 표시
    function displayMarker(locPosition,message){
        var marker=new kakao.maps.Marker({
            map:map,
            position:locPosition
        });

        var iwContent = message,
        iwRemovable = true;

        var infoindow = new kakao.maps.InfoWindow({
            content : iwContent,
            removable : iwRemovable
        });
        /*infoindow.open(map, marker);*/

        map.setCenter(locPosition);
    }



   
    //전달받은 주소 문자열을 좌표값으로 반환 후 marker생성하여 court_marker에 추가
    function getLatLng(address){
        geocoder.addressSearch(address,function(result,status){
            if (status == kakao.maps.services.Status.OK){
                var coords = new kakao.maps.LatLng(result[0].y, result[0].x);

                var marker = new kakao.maps.Marker({
                    map : map,
                    position : coords
                });
                
                court_markers.push(marker);
            }
        });
    }

    for (var i = 0; i < objs.length ; i++){
        getLatLng(objs[i]['host']['court_location']);
    };


    //경기 장소 마커 표시
    for (var i = 0 ; i < court_markers.length ; i++){
        court_markers[i].setMap(map);
    };

</script>
{% endblock %}

Veteran/templates/games/main.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=91ea5fd278223521e857ad81684db507&libraries=services"></script>
    <title>Main</title>
</head>
<body>
    {% load static %}
    <div class="header">
        <div class="imgcon2"><img src="{% static 'img/veteran_logo.png' %}" alt=""></div>
        <ul class="navbar" style="list-style:none;">
            <p style="color:white;">{{ user.username }}</p>
            <li class="nav-item"><a href="{% url 'Account:mypage' %}">👤 내 정보</a></li>
            {% if user.is_host %}
            <li class="nav-item"><a href="{% url 'Game:hostGame' %}">🏀 경기 등록</a></li>
            {% endif %}
        </ul>
    </div>
    <div class="wrapper">
        <div class="items">
            <!--지도 표시 부분-->
            <div class="map" id='map'></div>

            <!--경기 리스트 부분-->
            <div class="right">
                <div class="listy">
                    <div id="line">
                        <div class="up">
                            <div style="font-size: x-large; color: rgb(47, 48, 58); text-align:center;">게임 리스트</div>
                        </div>
                    </div>
                    <div class="details">
                        {% if message %}
                            <div class="error_block" style="display:flex; flex-direction:row; justify-content:center;">
                                <div style="color: red;">{{ message }}</div>
                            </div>
                        {% endif %}
                        <div class="games">
                            {% for game in game_list %}
                            <div class="game">
                                <div>
                                     {{ game.host }}       {{ game.numOfParticipation }}/{{ game.numOfRecruitment }}
                                </div>
                                <div>
                                    {{ game.start_datetime }}  
                                    <a class="participate" href="{% url 'Game:participate' game.id %}">참가신청<a>
                                </div>
                            </div>
                            {% endfor %}
                            <div class="page">
                                {% if game_list.has_previous %}
                                    <a class="page-link" style="float: left;" id="page_link" href="?page={{ game_list.previous_page_number }}">이전</a>
                                {% else %}
                                    <a class="page-link" style="float: left;" id="page_link" tabindex="-1" aria-disabled="true" href="#">이전</a>
                                {% endif %}
                                {% if game_list.has_next %}
                                    <a class="page-link" style="float: right;" id="page_link" href="?page={{ game_list.next_page_number }}">다음</a>
                                {% else %}
                                    <a class="page-link" style="float: right;" id="page_link" tabindex="-1" aria-disabled="true" href="#">다음</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
        </div>

    </div>


    <script>
        //지도 생성
        var container = document.getElementById('map');
        var option = {
            center : new kakao.maps.LatLng(37.59727,127.05884),
            level:3
        };

        var games = [];
        {% for game in game_list %}
            games.push({
                id : "{{ game.id }}",
                host : "{{ game.host }}",
                start_datetime : "{{ game.start_datetime }}",
                end_datetime : "{{ game.end_datetime }}",
                numOfRecruitment : "{{ game.numOfRecruitment }}",
                numOfParticipation : "{{ game.numOfParticipation }}",
                court_location : "{{ game.court_location }}"
            });
        {% endfor %}
        

        const map = new kakao.maps.Map(container,option);
        const court_markers=[];

        // 주소-좌표 변환 객체 생성
        var geocoder = new kakao.maps.services.Geocoder();


        //현재 사용자 위치 좌표 반환 메소드
        function getCurrentLocation(){
            if (navigator.geolocation){
                navigator.geolocation.getCurrentPosition(function(position){
                    var lat=position.coords.latitude,
                    lon=position.coords.longitude;
                    var locPosition=new kakao.maps.LatLng(lat,lon)
                });
            }else {
                var locPosition=new kakao.maps.LatLng(33.450701,126.590667);
            }
            return locPosition;
        }

        //사용자 위치 지도에 표시    
        if (navigator.geolocation){
            navigator.geolocation.getCurrentPosition(function(position){
                var lat=position.coords.latitude,
                lon=position.coords.longitude;
                
                var locPosition=new kakao.maps.LatLng(lat,lon),
                message='here';


                map.setCenter(locPosition);
                


                displayMarker(locPosition,message);
            });
            } 
            else {
                var locPosition=new kakao.maps.LatLng(33.450701,126.590667),
                message="error!"
                displayMarker(locPosition,message);
            }


        //마커 표시
        function displayMarker(locPosition,message){
            var marker=new kakao.maps.Marker({
                map:map,
                position:locPosition
            });

            var iwContent = message,
            iwRemovable = true;

            var infoindow = new kakao.maps.InfoWindow({
                content : iwContent,
                removable : iwRemovable
            });
            /*infoindow.open(map, marker);*/

            map.setCenter(locPosition);
        }



       
        //전달받은 주소 문자열을 좌표값으로 반환 후 marker생성하여 court_marker에 추가
        function getLatLng(address){
            geocoder.addressSearch(address,function(result,status){
                if (status == kakao.maps.services.Status.OK){
                    var coords = new kakao.maps.LatLng(result[0].y, result[0].x);

                    var marker = new kakao.maps.Marker({
                        map : map,
                        position : coords
                    });
                    
                    court_markers.push(marker);
                }
            });
        }

        for (var i = 0; i < games.length ; i++){
            getLatLng(games[i]['court_location'])
        }


        //경기 장소 마커 표시
        for (var i = 0 ; i < court_markers.length ; i++){
            court_markers[i].setMap(map);
        };

    </script>


    
</body>
</html>

Veteran/templates/games/pay.html
<div class="row mt-5">
    <h1 class="col-12 text-center my-5">KAKAO PAY</h1>
    <form method="post" class="col-12 text-center">
      {% csrf_token %}
      <button class="btn btn-warning">카카오페이로 결제하기</button>
    </form>
  </div>

Veteran/templates/games/set_game.html
{% extends 'base.html' %}
{% block head %}
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="/static/css/myInfo.css">
{% endblock %}

{% block style %}
{% endblock %}

{% block contnet %}
    <body style="display:flex; flex-direction:column">
        {% load static %}
        <div style="display:flex; justify-content :space-around;">
            <div style="background-color : beige; width:800px; height : 500px; margin-top:50px;">
                <form name="game_maker"action="{% url 'Game:registerGame' %}" method="POST">
                    {% csrf_token %}
                    <div class ="box" style="display:flex; flex-direction:column;">
                        <div>
                            <h1>새 경기</h1>
                        </div>
                        <div>
                            <h1>호스트</h1>
                            <h1>{{ host.group_name }}</h1>
                        </div>
                        <div>
                            <h1>농구장 주소</h1>
                            <h1>{{ host.court_location }}</h1>
                        </div>
                        <div style="display : flex; justify-content : space-around;">
                            <h1>인원수</h1>
                            <input type='number' name='numOfRecruitment' min='1' max='18' oninput="document.getElementById('value1').innerHTML=this.value;"></input>
                            <div id="value1"></div>
                        </div>
                        <div>
                            <input type="datetime-local" id="start_datetime" name="start_datetime" oninput="setEndtime()"></input>
                            <input type="datetime-local" id="end_datetime" name="end_datetime" ></input>
                        </div>
                        <div>
                        <button type="submit" class="btn">경기 등록</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <script>
            document.getElementById('start_datetime').value = new Date().toISOString().slice(0,16);
            document.getElementById('end_datetime').value = new Date().toISOString().slice(0,16);
            document.getElementById('start_datetime').setAttribute('min',new Date().toISOString().slice(0,16));

            function setEndtime(){
                document.getElementById('end_datetime').setAttribute('min',document.getElementById('start_datetime').value);
            };
        </script>
    </body>

{% endblock %}