Veteran/Game/urls.py
from django.urls import path
from . import views

app_name='Game'

urlpatterns=[
    path('gamelist/', views.gamelist, name = 'gamelist'),
    path('participate/<int:id>/', views.participate, name = 'participate'),
    path('hostGame/', views.hostGame, name = 'hostGame'),
    path('registerGame/', views.registerGame, name="registerGame"),
    path('payment/', views.payment, name='payment'),
]

Veteran/Veteran/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import urls

from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.welcome , name='welcome'),
    path('accounts/',include('accounts.urls')),
    path('games/',include('games.urls')),
]

Veteran/accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'

urlpatterns=[
    path('login', views.login, name='login'),
    path('logout/', views.logout,name='logout'),
    path('signup/', views.signup, name='signup'),
    path('mypage/',views.mypage, name = 'mypage' ),
    #path('myinfo', views.updateUserInfo, name='updateUserInfo'),
    path('host_form', views.reqHostAthority, name = 'reqHostAthority'),
    path('hostrequests/', views.lookupReq, name ='lookupReq'),
    path('acceptReq/', views.acceptReq, name='acceptReq'),
    path('rejectReq/', views.rejectReq, name='rejectReq'),
    #path('deleteReq/',views.deleteReq,name='deleteReq'),
    path('lookupRecord/', views.lookupRecord, name='lookupRecord'),
    path('lookupMyReview/', views.lookupMyReview, name='lookupMyReview'),
    path('leaveReview/', views.leaveReview, name='leaveReview'),
]

Veteran/games/urls.py
from django.urls import path
from . import views

app_name='games'


urlpatterns=[
    path('gamelist/', views.gamelist, name = 'gamelist'),
    path('participate/', views.participate, name = 'participate'),
    path('newgame/', views.newgame, name = 'newgame'),
    
]

Veteran/templates/base.html
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        <title>VETERAN</title>
        {% block head %}
        {% endblock %}
        
        <style>
          main{
            width : 1000px;
          }
        {% block style %}
        {% endblock %}
        </style>
    </head>
    <body>
        <div>
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">
                  <a class="navbar-brand" href="{% url 'accounts:login' %}">Veteran</a>
                  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                  </button>
                  <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                      <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'welcome' %}">Home</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'games:gamelist' %}">Games</a>
                      </li>
                      {% if user.is_superuser %}
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:lookupReq' %}">Host Management</a>
                      </li>
                      {% endif %}
                      {% if user.is_host %}
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'games:newgame' %}">Host Game</a>
                      </li>
                      {% endif %}
                      {% if user.is_active %}
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:logout' %}">Logout {{ user.nickname }}</a>
                      </li>
                      {% else %}
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                      </li>
                      {% endif %}
                      <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                          My Info
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                          <li><a class="dropdown-item" href="{% url 'accounts:lookupMyReview' %}">My Review</a></li>
                          <li><a class="dropdown-item" href="{% url 'accounts:lookupRecord' %}">Participated Games</a></li>
                          <li><hr class="dropdown-divider"></li>
                          <li><a class="dropdown-item" href="{% url 'accounts:reqHostAthority' %}">Host Application</a></li>
                        </ul>
                      </li>
                      
                    </ul>
                  </div>
                </div>
              </nav>
        </div>

        {% for message in messages %}
          <div class="alert {{ message.tags }} alert-auto-dismissible alert-dismissible notification-container text-center" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
          </div>
        {% endfor %}
        
        <div class="main">
        {% block content %}
        {% endblock %}
        </div>

    </body>
    <script>
      window.setTimeout(function() {
        $(".alert-auto-dismissible").fadeTo(500, 0).slideUp(500, function(){
            $(this).remove();
        });
      }, 2000);
    </script>
</html>