Veteran/Account/urls.py
from django.urls import path
from . import views

app_name='Account'

urlpatterns=[
    path('',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    path('signup/', views.signup, name='signup'),
    path('mypage/',views.mypage, name = 'mypage' ),
    path('reqHostAthority/', views.reqHostAthority, name = 'reqHostAthority'),
    path('lookupReq/', views.lookupReq, name ='lookupReq'),
    path('approveReq/',views.approveReq,name='approveReq'),
    path('deleteReq/',views.deleteReq,name='deleteReq'),
    path('lookupRecord/', views.lookupRecord, name='lookupRecord'),
    path('lookupMyReview/', views.lookupMyReview, name='lookupMyReview'),
    path('leaveReview/', views.leaveReview, name='leaveReview'),
]

Veteran/Game/urls.py
from django.urls import path
from . import views

app_name='Game'

urlpatterns=[
    path('gamelist/', views.gamelist, name = 'gamelist'),
    path('participate/<int:id>/', views.participate, name = 'participate'),
    path('hostGame/', views.hostGame, name = 'hostGame'),
    path('registerGame/', views.registerGame, name="registerGame"),
    path('payment/', views.payment, name='payment'),
]

Veteran/Veteran/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import urls

from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.welcome , name='welcome'),
    path('accounts/',include('accounts.urls')),
    path('games/',include('games.urls')),
]

Veteran/accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'

urlpatterns=[
    path('login', views.login, name='login'),
    path('logout/', views.logout,name='logout'),
    path('signup/', views.signup, name='signup'),
    path('mypage/',views.mypage, name = 'mypage' ),
    #path('myinfo', views.updateUserInfo, name='updateUserInfo'),
    path('host_form', views.reqHostAthority, name = 'reqHostAthority'),
    path('hostrequests/', views.lookupReq, name ='lookupReq'),
    path('acceptReq/', views.acceptReq, name='acceptReq'),
    path('rejectReq/', views.rejectReq, name='rejectReq'),
    #path('deleteReq/',views.deleteReq,name='deleteReq'),
    path('lookupRecord/', views.lookupRecord, name='lookupRecord'),
    path('lookupMyReview/', views.lookupMyReview, name='lookupMyReview'),
    path('leaveReview/', views.leaveReview, name='leaveReview'),
]

Veteran/Account/forms.py
from django import forms
from .models import Host

class HostForm(forms.ModelForm):
    
    class Meta:
        model = Host
        fields = ['host', 'group_name', 'court_location', 'intro']
        

Veteran/Account/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt

import json

# from Veteran.Veteran.Account import models
from Game.models import Game, Game_Participants
from .models import User, Host, HostApplication, Review


# Create your views here.
def login(request):
    if request.user.is_authenticated:
        return redirect('Game:gamelist')
    else:
        if request.method=="POST":
            username=request.POST['username']
            password=request.POST['password']           
            user=auth.authenticate(
                request,
                username=username,
                password=password
            )
            if user is not None:
                auth.login(request,user)
                return redirect('Game:gamelist')
            else:
                return render(request, 'Account/welcome_login.html',{'error':"일치하는 사용자가 없습니다"})
        else:
            return render(request,'Account/welcome_login.html')
    
    
def logout(request):
    auth.logout(request)
    return redirect('Account:login')
    

##수정필요
def signup(request):
    if request.method == "POST":
        if request.POST['pw'] == request.POST['cpw']:
            user = User.objects.create_user(username=request.POST['email'], password=request.POST['pw'], nickname=request.POST['nickname'], phone=request.POST['phone'])
            auth.login(request,user)
            return redirect('Account:mypage')
        else:
            return render(request,'Account/join_page.html',{'error':'회원 가입 정보를 확인해주세요'})
    return render(request,'Account/join_page.html')
    
def mypage(request):
    return render(request, 'Account/myinfo.html')


@csrf_exempt
def reqHostAthority(request):
    if request.method=="POST":
        host = HostApplication()
        host.host = request.user
        host.group_name = request.POST["team_name"]
        host.court_location = request.POST["fullAddress"]
        host.intro = request.POST["intro"]
        host.save()
        return redirect('Account:mypage')
    return render(request,'Account/host_application.html')



def lookupReq(request):
    request_list=HostApplication.objects.all()
    return render(request, 'Account/Host approval.html',{"request_list":request_list})



def approveReq(request):
    if request.method=='POST':
        req_id=User.objects.get(username=request.POST['host'])
        req_host=HostApplication.objects.get(host=req_id)
        if req_host:
            new_host=Host()
            new_host.host=req_id
            new_host.group_name=req_host.group_name
            new_host.court_location=req_host.court_location
            new_host.intro=req_host.intro
            new_host.save()
            req_host.delete()
            return redirect('Account:lookupReq')
        return redirect('Account:lookupReq')
    return redirect('Account:lookupReq')

def deleteReq(request):
    if request.method=='POST':
        req_id=User.objects.get(username=request.POST['host'])
        req_host=HostApplication.objects.get(host=req_id)
        req_host.delete()
    return redirect('Account:lookupReq')


def lookupRecord(request):
    id_participants = {}
    id_game = {}
    scheduled_games = []
    participated_games = Game_Participants.objects.filter(user = request.user)
    
    for game in participated_games:
        if game.game.isProgressed():
            tempGame = Game_Participants.objects.filter(game = game.game)
            for g in tempGame:
                if g.game.id in id_participants:
                    id_participants[g.game.id].append((g.user.id, g.user.username))
                else:
                    id_participants[g.game.id] = [(g.user.id, g.user.username)]
            id_game[game.game.id] = game.game.toDict()
            id_game[game.game.id]['host']=game.game.host.group_name
        else:
            scheduled_games.append(game.game.toDict())
    return render(request, 'Account/games_review.html',{"id_participants" : id_participants, "id_game":id_game,"scheduled_games" : scheduled_games[:10]})


def leaveReview(request):
    if request.method == 'POST':
        review = Review()
        review.reviewer = request.user
        review.reviewee = User.objects.get(username = request.POST['reviewee_username'])
        review.comment_type = request.POST['p_num']
        review.rating = request.POST['rating']
        review.save()
        return redirect('Account:lookupRecord')
        
        
        
        
    return redirect('Account:lookupRecord')


def lookupMyReview(request):
    reviews=Review.objects.filter(reviewee = request.user).order_by('-id')
    rating=None
    for review in reviews:
        if rating == None:
            rating = review.rating
        else:
            rating += review.rating
    if rating == None:
         return render(request, 'Account/my_estimation.html', {"reviews" : reviews })
    else:
        rating="%.1f"%(rating/len(reviews))
        return render(request, 'Account/my_estimation.html', {"reviews" : reviews[:3] , "rating":rating})

Veteran/accounts/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.core.paginator import Paginator
from django.db import transaction


from games.models import Game, GameParticipant
from .models import User, Host, HostApplication, Review
from .forms import UserCreationForm, HostForm



# Create your views here.


def login(request):
    if request.user.is_authenticated:
        return redirect('games:gamelist')
    else:
        if request.method == "POST":
            form = AuthenticationForm(request, request.POST)
            if form.is_valid():
                auth.login(request, form.get_user())
                return HttpResponseRedirect('/games/gamelist')
            return render(request, 'accounts/login_form.html', {'form' : form, "error" : "로그인 정보가 정확하지 않습니다."})
        else:
            form = AuthenticationForm()
        return render(request, 'accounts/login_form.html', {'form' : form,})


def signup(request):
    if request.user.is_authenticated:
        return redirect('games:gamelist')
    else:
        if request.method == "POST":
            form = UserCreationForm(request.POST)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect('/accounts/login')
            return render(request,'accounts/signup_form.html',{'form' : form,'error':'회원 가입 정보를 확인해주세요'})
        else:
            form = UserCreationForm()
        return render(request, 'accounts/signup_form.html',{'form' : form})
                    

def logout(request):
    auth.logout(request)
    return redirect('accounts:login')
    
    
def mypage(request):
    return render(request, 'accounts/myinfo.html')


def reqHostAthority(request):
    if request.method=="POST":
        form = HostForm(request.POST)
        try:
            with transaction.atomic():
                if form.is_valid():
                    hostform = HostApplication()
                    hostform.host = request.user
                    hostform.group_name = request.POST['group_name']
                    hostform.court_location = request.POST['court_location'] + " " + request.POST['court_detail_location']
                    hostform.intro = request.POST['intro']
                    hostform.save()
                else:
                    messages.warning(request, "올바르지 않는 입력값입니다.")
                    return redirect('accounts:reqHostAthority')
        except Exception as e:
            messages.warning(request, "올바르지 않는 입력값입니다.")
            return render(request, 'accounts/host_application.html', {'form' : form})
        return redirect('games:gamelist')
    else:
        form = HostForm()
        return render(request, 'accounts/host_application.html', {'form' : form})




def lookupReq(request, message = None):
    host_requests = HostApplication.objects.all()
    paginator = Paginator(host_requests, 10)
    context = {}
    context["page_obj"] = paginator.get_page(request.GET.get('page',1))
    if message:
        for msg in message.keys():
            messages.warning(request, message[msg])
    return render(request, 'accounts/host_req_list.html', context)


def acceptReq(request):
    if request.method == "POST":
        try:
            req = HostApplication.objects.get(id = request.POST['req_id'])
        except:
            messages.warning(request, "해당 호스트 신청을 찾을 수 없습니다.")
            return redirect('accounts:lookupReq')
        if req:
            try:
                with transaction.atomic():
                    hostuser = User.objects.get(id = req.host.id)
                    hostuser.is_host = True
                    newhost = Host()
                    newhost.host = hostuser
                    newhost.group_name = req.group_name
                    newhost.court_location = req.court_location
                    newhost.intro = req.intro
                    newhost.save()
                    hostuser.save()
                    req.delete()
            except Exception as e:
                messages.warning(request, "해당 호스트 승인이 불가능합니다.")
                return redirect('accounts:lookupReq')
            messages.success(request, "승인이 완료되었습니다.")
            return redirect('accounts:lookupReq')
    return redirect('accounts:lookupReq')



def rejectReq(request):
    if request.method == "POST":
        try:
            with transaction.atomic():
                req = HostApplication.objects.get(id = request.POST['req_id'])
                req.delete()
        except Exception as e:
            messages.warning(request, "해당 호스트 거절이 불가능합니다.")
            return redirect('accounts:lookupReq')
        messages.success(request, "거절이 완료되었습니다.")
        return redirect('accounts:lookupReq')
    return redirect('accounts:lookupReq')


def lookupRecord(request):
    id_participants = {}
    id_game = {}
    scheduled_games = []
    participated_games = Game_Participant.objects.filter(user = request.user)
    
    for game in participated_games:
        if game.game.isProgressed():
            tempGame = Game_Participant.objects.filter(game = game.game)
            for g in tempGame:
                if g.game.id in id_participants:
                    id_participants[g.game.id].append((g.user.id, g.user.username))
                else:
                    id_participants[g.game.id] = [(g.user.id, g.user.username)]
            id_game[game.game.id] = game.game.toDict()
            id_game[game.game.id]['host']=game.game.host.group_name
        else:
            scheduled_games.append(game.game.toDict())
    return render(request, 'accounts/games_review.html',{"id_participants" : id_participants, "id_game":id_game,"scheduled_games" : scheduled_games[:10]})


def leaveReview(request):
    if request.method == 'POST':
        review = Review()
        review.reviewer = request.user
        review.reviewee = User.objects.get(username = request.POST['reviewee_username'])
        review.comment_type = request.POST['p_num']
        review.rating = request.POST['rating']
        review.save()
        return redirect('accounts:lookupRecord')
    return redirect('accounts:lookupRecord')


def lookupMyReview(request):
    reviews=Review.objects.filter(reviewee = request.user).order_by('-id')
    rating=None
    for review in reviews:
        if rating == None:
            rating = review.rating
        else:
            rating += review.rating
    if rating == None:
         return render(request, 'accounts/my_estimation.html', {"reviews" : reviews })
    else:
        rating="%.1f"%(rating/len(reviews))
        return render(request, 'accounts/my_estimation.html', {"reviews" : reviews[:3] , "rating":rating})

Veteran/templates/accounts/evaluation form.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100&display=swap" rel="stylesheet">
    <title>personal game infos</title>
    <style>
        .star-rating {
            display: flex;
            flex-direction: row-reverse;
            font-size: 2.25rem;
            line-height: 2.5rem;
            justify-content: space-around;
            padding: 0 0.2em;
            text-align: center;
            width: 5em;
          }
           
          .star-rating input {
            display: none;
          }
           
          .star-rating label {
            -webkit-text-fill-color: transparent; /* Will override color (regardless of order) */
            -webkit-text-stroke-width: 2.3px;
            -webkit-text-stroke-color: #2b2a29;
            cursor: pointer;
          }
           
          .star-rating :checked ~ label {
            -webkit-text-fill-color: gold;
          }
           
          .star-rating label:hover,
          .star-rating label:hover ~ label {
            -webkit-text-fill-color: #fff58c;
          }

          

    </style>
</head>

<body>
    <form class="complete_btn">
        <div class="star-rating space-x-4 mx-auto">
            <input type="radio" id="5-stars" name="rating" value="5" v-model="ratings"/>
            <label for="5-stars" class="star pr-4">★</label>
            <input type="radio" id="4-stars" name="rating" value="4" v-model="ratings"/>
            <label for="4-stars" class="star">★</label>
            <input type="radio" id="3-stars" name="rating" value="3" v-model="ratings"/>
            <label for="3-stars" class="star">★</label>
            <input type="radio" id="2-stars" name="rating" value="2" v-model="ratings"/>
            <label for="2-stars" class="star">★</label>
            <input type="radio" id="1-star" name="rating" value="1" v-model="ratings" />
            <label for="1-star" class="star">★</label>
        </div>
        <div>
        <p>선수의 매너를 평가해주세요!</p>
        <input type='radio' name='p_num' value='5' checked/> 
        <label>완벽한 베테랑이었어요!</label><br>
        <input type='radio' name='p_num' value='4' /> 
        <label>매너가 좋은 선수에요!</label><br>
        <input type='radio' name='p_num' value='3' /> 
        <label>괜찮았어요</label><br>
        <input type='radio' name='p_num' value='2' /> 
        <label>독단적인 플레이를 해요</label><br>
        <input type='radio' name='p_num' value='1' /> 
        <label>위험하게 플레이해요</label><br>
        </div>
        <br>
        <br>
        <input type="submit" id="리뷰 제출">
    </form>





</body>

Veteran/templates/accounts/host_application.html
{% extends 'base.html' %}
{% block head %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100&display=swap" rel="stylesheet">

{% endblock %}

{% block style %}
{% endblock %}

{% block content %}
<div class="wrap">
    <div class = "header">
        <div class="right">
            <h1>베테랑</h1>
            <h2>호스트 신청</h2>
            <section class="host-form">
                <form action="{% url 'accounts:reqHostAthority' %}" id="form1" method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <span class="address-area">
                        <input type="button" id="find_address" onclick="sample6_execDaumPostcode()" value="주소번호 찾기"><br>
                    </span>
                  
                    
                    <button type="submit" class="btn btn-primary">호스트 신청</button>
                </form>
            </section>
        </div>
        <script src="//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"></script>
    <script>
        function sample6_execDaumPostcode() {
            new daum.Postcode({
                oncomplete: function(data) {
                    
                    var addr = ''; // 주소 변수
                    var extraAddr = ''; // 참고항목 변수
                    var fullAddress='';
    
                    //사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.
                    if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우
                        addr = data.roadAddress;
                    } else { // 사용자가 지번 주소를 선택했을 경우(J)
                        addr = data.jibunAddress;
                    }
    
                    // 사용자가 선택한 주소가 도로명 타입일때 참고항목을 조합한다.
                    if(data.userSelectedType === 'R'){
                        // 법정동명이 있을 경우 추가한다. (법정리는 제외)
                        // 법정동의 경우 마지막 문자가 "동/로/가"로 끝난다.
                        if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){
                            extraAddr += data.bname;
                        }
                        // 건물명이 있고, 공동주택일 경우 추가한다.
                        if(data.buildingName !== '' && data.apartment === 'Y'){
                            extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);
                        }
                        // 표시할 참고항목이 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.
                        if(extraAddr !== ''){
                            extraAddr = ' (' + extraAddr + ')';
                        }
                    
                    }
    
                    // 우편번호와 주소 정보를 해당 필드에 넣는다.
                    document.getElementById("id_court_location").value = (addr+extraAddr);
                }
            }).open();
        }
    </script>
{% endblock %}

Veteran/templates/accounts/host_req_list.html
{% extends 'base.html' %}
{% block head %}
{% endblock %}

{% block style %}
{% endblock %}

{% block content %}

<div>
    {% for req in page_obj %}
        <form id="req_form" method = "POST">
            {% csrf_token %}
            <input name="req_id" value="{{ req.id }}" >
            <p>{{ req.group_name }}</p>
            <p>{{ req.intro }}</p>
            <p>{{ req.court_location }}</p>
            <button type="submit"   onclick='req_acc_click()'>승인</button>
            <button type="submit"  onclick='req_rej_click()'>거절</button>
        </form>
    {% endfor %}
    <div class="pagination">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}
        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}

    </div>
</div>
<script>
    
    function req_acc_click(){
        req_form = document.getElementById('req_form');
        req_form.setAttribute('action', "{% url 'accounts:acceptReq' %}");
    };

    function req_rej_click(){
        req_form = document.getElementById('req_form');
        req_form.setAttribute('action', "{% url 'accounts:rejectReq' %}");
    };

    window.setTimeout(function() {
        $(".alert-auto-dismissible").fadeTo(500, 0).slideUp(500, function() {
            $(this).remove();
        });
    }, 2000);
</script>
{% endblock %}

Veteran/templates/accounts/login.html
{% extends 'base.html' %}
{% block head %}
{% endblock %}

{% block style %}
    <style>
        .login-form {
            max-width : 700px;
        }
    </style>
    
{% endblock %}

{% block content %}

<div class="login-form" id="login-form">
    <form action="{% url 'accounts:login' %}" method="POST">
        {% csrf_token %}
        <div class="mb-3">
          <label for="exampleInputEmail1" class="form-label">ID</label>
          <input type="email" class="form-control" name="user_id" id="exampleInputEmail1" aria-describedby="emailHelp">
        </div>
        <div class="mb-3">
          <label for="exampleInputPassword1" class="form-label">Password</label>
          <input type="password" class="form-control" name="password" id="exampleInputPassword1">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
        <div class="form-floating">
            <div> 아직 회원이 아니신가요? <a href="{% url 'accounts:signup' %}"> 회원가입</a></div>
        </div>
    </form>
</div>
{% endblock %}

Veteran/templates/accounts/login_form.html
{% extends 'base.html' %}
{% block head %}
{% endblock %}

{% block style %}
    <style>
        .login-form {
            max-width : 700px;
        }
    </style>
    
{% endblock %}

{% block content %}

<div class="login-form" id="login-form">
    <form action="{% url 'accounts:login' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Submit</button>
        <div class="form-floating">
            <div> 아직 회원이 아니신가요? <a href="{% url 'accounts:signup' %}"> 회원가입</a></div>
        </div>
    </form>
</div>
{% endblock %}

Veteran/templates/accounts/myInfo.html
<!doctype html>
<html lang="ko">
    <head>
        <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="/static/css/myInfo.css">
        <style>
        /* --- nav css --- */
        .right navbar{
            float: right;
            display: flex;
            flex-direction: row;
            width: 100%;
            list-style-type: none;
            position: fixed;
            color: white;
        }
        nav-item{
            padding: 15px;
            cursor: pointer;
        }
    
        .navbar li{
            display: flex;
            float:right;
            padding: 0px 20px;
        }

        div {
            width: 100%;
            height: 100vh;
        }
        div.left {
            width: 40%;
            float: left;
            box-sizing: border-box;

            background: #2F303A;
        }
        div.right {
            width: 60%;
            float: right;
            box-sizing: border-box;

            background: #EBEBEB;
        }
        b {
          margin-top:70px;
          margin-bottom:50px;
        }
        ul {
            
            list-style-position: inside;
        }
        li {
            margin: 62px 0px;
        }
        </style>
    </head>
    <body>
    {% load static %}
        <div class="wrap">
            <div class = "header">
                <div class="left">
                <img 
                src = "{% static 'img/veteran_logo.png' %}"
                style= "margin-left: 50px; margin-top: 50px;"
                />
                <img 
                src = "{% static 'img/myInfoFixed.jpg' %}"
                style= "float: left; margin-top: 50px; width:100%;"
                />

                </div>
                <div class="right">
                    <ul class="navbar">
                        <li class="nav-item"><a href="{% url 'Account:login' %}">🏠 홈</a></li>
                    </ul>
                <b style = "color: #686868; display: table; margin-top:70; margin-left: 64px; margin-right: auto;">내 정보</b>
                <hr style="border: solid 3px #686868; margin-left: 50px; margin-right: 50px;">
                  <ul class ="nav">
                      <li><a href="{% url 'Account:lookupRecord' %}">🗓 경기일람 및 리뷰</a></li>
                      <li><a href="{% url 'Account:lookupMyReview' %}">📊 내 평가 보기</a></li>
                      {% if user.is_host %}
                      <li><a href="{% url 'Game:hostGame' %}">📃 경기 등록</a></li>
                      {% else %}
                        <li><a href="{% url 'Account:reqHostAthority' %}">📃 호스트 신청</a></li>
                      {% endif %}
                  </ul>
                  <hr style="border: solid 3px #686868; margin-left: 50px; margin-right: 50px;">
                  <ul class ="nav2">
                      <li><a href="{% url 'Account:logout' %}">🚪 로그아웃</a></li>
                      <!--<li><a href="#">🔐 회원해지</a></li>-->
                      {% if user.is_superuser %}
                        <li><a href="{% url 'Account:lookupReq' %}">호스트 신청 승인</a></li>
                      {% endif %}
                  </ul>
                </div>
            </div>
        </div>
    </body>
</html>

Veteran/templates/accounts/my_info_host.html
<!doctype html>
<html lang="ko">
    <head>
        <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100&display=swap" rel="stylesheet">
        <style>
        div {
            width: 100%;
            height: 100vh;
        }
        div.left {
            width: 40%;
            float: left;
            box-sizing: border-box;

            background: #2F303A;
        }
        div.right {
            width: 60%;
            float: right;
            box-sizing: border-box;

            background: #EBEBEB;
        }
        ul.nav{
            display: table;
            margin-left: 64px;
            margin-right: auto;
        }

        ul.nav2{
            display: table;
            margin-left: 64px;
            margin-right: auto;
        }
        
        b {
        margin-top:70px;
        margin-bottom:50px;
        }
        ul {
            
            list-style-position: inside;
        }
        li {
            margin: 62px 0px;
        }
        </style>
    </head>
    <body>
        <div class="wrap">
            <div class = "header">
                <div class="left">
                <img 
                src = "image/veteran logo.png"
                style= "margin-left: 50px; margin-top: 50px;"
                />

                <img 
                src = "image/myInfoFixed.jpg"
                style= "float: left; margin-top: 50px; width:100%;"
                />

                </div>
                <div class="right">
                <b style = "color: #686868; display: table; margin-top:70; margin-left: 64px; margin-right: auto;">내 정보</b>
                <hr style="border: solid 3px #686868; margin-left: 50px; margin-right: 50px;">
                    <ul class ="nav">
                        <li><a href="#">🗓 경기일람 및 리뷰</a></li>
                        <li><a href="#">📊 내 평가 보기</a></li>
                        <li><a href="#">⚜️ 호스팅 관리</a></li>
                    </ul>
                    <hr style="border: solid 3px #686868; margin-left: 50px; margin-right: 50px;">
                    <ul class ="nav2">
                        <li><a href="#">🚪 로그아웃</a></li>
                        <li><a href="#">🔐 회원해지</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </body>
</html>

Veteran/templates/accounts/signup_form.html
{% extends "base.html" %}
{% block head %}
<title>Sign up</title>
{% endblock %}

{% block style %}
{% endblock %}

{% block content %}
<div>
    <form action="{% url 'accounts:signup' %}" method="post">
      {% csrf_token %}
      {{ form }}
      {% if error %}
      <p>{{ error }}</p>
      {% endif %}
      <button type="submit" class="btn btn-primary">회원가입</button>
    </form>
</div>
{% endblock %}